# Generated by Django 4.1.3 on 2022-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('plataforms', models.CharField(max_length=100, verbose_name='plataforms')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('image', models.ImageField(null=True, upload_to='image/', verbose_name='image')),
            ],
        ),
    ]
